### ISSUE TITLE
when put this comand python beRoot.py i have this bug

### ISSUE THREAD

**Issue by devil67** [AlessandroZ/BeRoot#1]
$python beRoot.py
Traceback (most recent call last):
  File "beRoot.py", line 2, in <module>
    from beroot.run_checks import check_all, get_sofwares
  File "/home/kevin/Documenti/PENTEST/BeRoot/BeRoot/beroot/run_checks.py", line 1, in <module>
    from modules.checks.path_manipulation_checks import isRootDirectoryWritable, space_and_no_quotes, exe_with_writable_directory
  File "/home/kevin/Documenti/PENTEST/BeRoot/BeRoot/beroot/modules/checks/path_manipulation_checks.py", line 2, in <module>
    import win32con
ImportError: No module named win32con

**Comment by AlessandroZ** [comment]
I should do a list of dependency needed: 

I think only both are required: 
- Python for Windows Extensions: http://sourceforge.net/projects/pywin32/
- Impacket: https://github.com/CoreSecurity/impacket

**Comment by devil67** [comment]
right in window how i can run it?

**Comment by AlessandroZ** [comment]
You have a compiled binary here: https://github.com/AlessandroZ/BeRoot/releases
