### ISSUE TITLE
sudoers file - error

### ISSUE THREAD

**Issue by truesamurai** [AlessandroZ/BeRoot#22]
Hello,
The script is running fine, until sudoers file part. There I get this error:

Traceback (most recent call last):
  File "./beroot.py", line 28, in <module>
    run(arguments.password)
  File "/root/BeRoot/Linux/beroot/run.py", line 190, in run
    results = c()
  File "/root/BeRoot/Linux/beroot/run.py", line 73, in sudo_list
    rules = self.sudolist.rules_from_sudo_ll()
  File "/root/BeRoot/Linux/beroot/modules/sudo/sudo_list.py", line 53, in rules_from_sudo_ll
    sudo_rules = self._parse_sudo_list(sudo_list)
  File "/root/BeRoot/Linux/beroot/modules/sudo/sudo_list.py", line 68, in _parse_sudo_list
    user = sudo_list[sudo_list.index('User '):].split(' ')[1]
ValueError: substring not found

**Comment by AlessandroZ** [comment]
Hi, I need your `sudo -ll `output to understand the error.
