### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by leninisback** [AlessandroZ/BeRoot#24]
Hey, 

I tried to run for the first time with python 3.8.0 with windows and get this output: 
Traceback (most recent call last):
  File "xr.py", line 45, in <module>
    from lib.beroot.run import check_all, get_sofwares
  File "C:\Users\james\Desktop\Support-master\dev\lib\beroot\run.py", line 6, in <module>
    from .modules.checks.services_checks import check_services_creation_with_openscmanager, check_service_permissions
  File "C:\Users\james\Desktop\Support-master\dev\lib\beroot\modules\checks\services_checks.py", line 3, in <module>
    from ..objects.winstructures import OpenSCManager, SC_MANAGER_CREATE_SERVICE
  File "C:\Users\james\Desktop\Support-master\dev\lib\beroot\modules\objects\winstructures.py", line 66
    STANDARD_RIGHTS_REQUIRED        = 0x000F0000L

Do you get any idea why?

**Comment by AlessandroZ** [comment]
Sorry for my late answer. Use Python2.7 for now, I hope to do the portability soon.

**Comment by leninisback** [comment]
What? Dude, nobody use python2.7 anymore... 
I downvote
