### ISSUE TITLE
SyntaxError in modules\objects\winstructures.py

### ISSUE THREAD

**Issue by ghost** [AlessandroZ/BeRoot#32]
Traceback (most recent call last):
  File "C:\Users\0x00\Desktop\BeRoot\Windows\BeRoot\beroot.py", line 3, in <module>
    from beroot.run import check_all, get_sofwares
  File "C:\Users\0x00\Desktop\BeRoot\Windows\BeRoot\beroot\run.py", line 6, in <module>
    from .modules.checks.services_checks import check_services_creation_with_openscmanager, check_service_permissions
  File "C:\Users\0x00\Desktop\BeRoot\Windows\BeRoot\beroot\modules\checks\services_checks.py", line 3, in <module>
    from ..objects.winstructures import OpenSCManager, SC_MANAGER_CREATE_SERVICE
  File "C:\Users\0x00\Desktop\BeRoot\Windows\BeRoot\beroot\modules\objects\winstructures.py", line 66
    STANDARD_RIGHTS_REQUIRED        = 0x000F0000L
                                                ^
SyntaxError: invalid syntax

**Comment by ghost** [comment]
Fixed it, i had to remove a L.
