### ISSUE TITLE
BeRoot not working properly if system language is different from English

### ISSUE THREAD

**Issue by D3vil0p3r** [AlessandroZ/BeRoot#41]
Ciao @AlessandroZ 
I'm further testing BeRoot. I noted that if the system language is different from English, and you run BeRoot, you will get an error like:
```
Traceback (most recent call last):
  File "/usr/share/beroot/Linux/beroot.py", line 38, in <module>
    run(password)
  File "/usr/share/beroot/Linux/beroot/run.py", line 223, in run
    results = c()
              ^^^
  File "/usr/share/beroot/Linux/beroot/run.py", line 83, in sudo_list
    rules = self.sudolist.rules_from_sudo_ll()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/beroot/Linux/beroot/modules/sudo/sudo_list.py", line 53, in rules_from_sudo_ll
    sudo_rules = self._parse_sudo_list(sudo_list.decode())
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/beroot/Linux/beroot/modules/sudo/sudo_list.py", line 68, in _parse_sudo_list
    user = sudo_list[sudo_list.index('User '):].split(' ')[1]
                     ^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: substring not found
```
It occurs because in `sudo_list.py` it is searching for `User ` string from `sudo -S -ll` command output, but in different languages, like Italian, where `sudo -S -ll` could appear:
```
Corrispondenza voci Defaults per testuser su myhost:
    secure_path=/usr/local/sbin\:/usr/local/bin\:/usr/bin

Valori predefiniti per Runas e Command per testuser:
    Defaults!/usr/bin/visudo env_keep+="SUDO_EDITOR EDITOR VISUAL"

L'utente testuser può eseguire i seguenti comandi su myhost:

Sudoers entry: /etc/sudoers
    RunAsUsers: ALL
    RunAsGroups: ALL
    Comandi:
	ALL

Sudoers entry: /etc/sudoers.d/sudo_nopasswd_psd
    RunAsUsers: ALL
    Opzioni: !authenticate
    Comandi:
	/usr/bin/psd-overlay-helper
```
you have `L'utente` instead of `User`string.

Do you have an idea how to manage the case with different languages to manage this issue?

Thanks

**Comment by D3vil0p3r** [comment]
Here I propose you the PR that fixes the mentioned issue in order to make BeRoot independent from different system languages: https://github.com/AlessandroZ/BeRoot/pull/42

@AlessandroZ can you please give a look and merge it if you agree? Thanks again.

**Comment by AlessandroZ** [comment]
Thanks a lot for your PR !
